### ISSUE TITLE
Move to miniprofiler project

### ISSUE THREAD

**Issue by madelynnblue** [yeller/clojure-miniprofiler#1]
Are you interested in moving this to the main [miniprofiler project](http://github.com/miniprofiler)?

**Comment by tom-pang** [comment]
@mjibson I'd like to get at least an initial round of feedback from folk using it in production first.

There are a few things to finish off feature-wise as well before it's fully compatible (for example, clojure-miniprofiler doesn't profile POST or AJAX requests like the other miniprofilers do).

**Comment by tom-pang** [comment]
@mjibson : I'm also unsure what the state of things are with regards to process or whatever on moving it to the official project:

e.g. do I have to change the licensing, what kinds of contribution process is there (do I just take PRs etc),  will you folk want documentation moved to the official site (I'm not even sure that's setup for that right now), and so on.

**Comment by madelynnblue** [comment]
I'm not sure about the license issues so maybe it's best to wait for now. But otherwise you can handle it however you like. If you ever want to move forward I'm sure we can work it out.
